# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: amazing_dev
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>
  encoding: UTF8

test:
  <<: *default
  database: amazing_dev
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: amazing_dev
  username: <%= Rails.application.secrets[:database][:user] %>
  password: <%= Rails.application.secrets[:database][:password] %>
